### ISSUE TITLE
Some refactoring (Database, scapy)

### ISSUE THREAD

**Issue by TB-DevAcc** [jo-jstrm/SmartHomeBuddy#47]
Is this in the correct order? Initial DB setup reads as if it should be before starting influx.
https://github.com/jo-jstrm/SmartHomeBuddy/blob/ced0ca0fee9fef13d44af8377d8258df22cb101e/device-identifier/shbdeviceidentifier/db.py#L122-L125

-------------------------

This warning pops up constantly, should it be a trace instead? Or is this a bug?
https://github.com/jo-jstrm/SmartHomeBuddy/blob/ced0ca0fee9fef13d44af8377d8258df22cb101e/device-identifier/shbdeviceidentifier/db.py#L189-L192

-------------------------

Any ideas in how to get rid of the  CryptographyDeprecationWarning? It is not relevant for our use case and is already fixed in the upcoming scapy release, but would be nice to filter it out until then. Unfortunately a `warnings.filter()` call does not suffice, since it is raised by scapy internally. Calling the filter before importing scapy does not work either, since the warning is raised as soon as `CryptoDeprecationWarning` class is imported from cryptography.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/25723425/184337540-ad114f64-64a9-4632-ac53-e1bb0562d741.png">

Suppressing all scapy messages, as suggested on [SO](https://stackoverflow.com/questions/13249341/suppress-scapy-warning-message-when-importing-the-module), seems overkill.

**Comment by TB-DevAcc** [comment]
Changed the warning to a trace in #48 and suppressed the warning (not a great solution). We can change it back later, but for the release it might be beneficial to clean it up first.

**Comment by jo-jstrm** [comment]
> This warning pops up constantly, should it be a trace instead? Or is this a bug?

Warning seems overkill to me. I think debug would be appropriate. I think it is important information for debugging, i.e., knowing whether a setup has already been run or not. 

> Is this in the correct order? Initial DB setup reads as if it should be before starting influx.

The order is correct. In order to set up InfluxDB, we must first start (=run) it. Maybe renaming `start_InfluxDB` to `run_InfluxDB` might prevent confusion?

> Any ideas in how to get rid of the CryptographyDeprecationWarning?

Currently not :(

**Comment by TB-DevAcc** [comment]
While testing I noticed that our Database class has a `start()` method but not a `stop()` method. This is a little counterintuitive and should probably be addressed. A wrapper around `stop_InfluxDB()` might be the easiest?

**Comment by TB-DevAcc** [comment]
Added a `db.stop()` method in #93. Closing this now, a complete refactoring of the Database might have to be done in the future though.
